# Generated by Django 2.1.5 on 2019-01-27 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=400)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('facebook_link', models.URLField(blank=True)),
                ('follows', models.ManyToManyField(blank=True, to='profile_app.ProfileInfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profileinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
